### PR TITLE
GenerateContent: fix relative image src as well

### PR DESCRIPTION
**Pull request by JanTvrdik**
See https://componette.com/nextras/mail-panel/ vs. https://github.com/nextras/mail-panel#nextras-mail-panel

Hopefully this will resolve this.

### CODE REVIEW

**Comment by JanTvrdik** [comment]
See also [how does Packages handle this](https://github.com/composer/packagist/blob/a07b9f715b301a414f7a12f166432df7e9b956e1/src/Packagist/WebBundle/Package/Updater.php#L395-L476)

**Comment by JanTvrdik** [comment]
ping

**Comment by f3l1x** [comment]
I'll merge it in next week. With more changes. Thank you for PR.

:-)

**Comment by f3l1x** [comment]
@JanTvrdik Thank you.

**Pull request merged**
